name: "Docker Actions"

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: meow
        uses: ./.github/actions/cat-facts
        id: cat
      
      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fact: ${{ steps.cat.outputs.fact }}
          title: "a cat fact for you"
